lambda_function_name    = "rocket-project-prod-lambda"
project_name            = "rocket-project"
environment             = "prod"
aws_region              = "sa-east-1"
s3_bucket_name          = "rocket-project-prod-bucket-idempotency"
aws_statefile_s3_bucket = "rocket-project-statefiles"
aws_lock_dynamodb_table = "rocket-projec-terraform-lock"